name: astroyorumai
description: "Turkish Astrology Application with Pro Features"
publish_to: 'none'
version: 2.1.3+1

environment:
  sdk: '^3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.0.0
  intl: ^0.18.0
  shared_preferences: ^2.1.0
  provider: ^6.0.0
  table_calendar: ^3.0.9
  pdf: ^3.10.0
  printing: ^5.11.0
  share_plus: ^7.0.0
  path_provider: ^2.0.0
  flutter_local_notifications: ^16.0.0
  timezone: ^0.9.0
  permission_handler: ^10.4.0
  geolocator: ^9.0.0
  geocoding: ^2.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  mockito: ^5.4.2
  crypto: ^3.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf