services:
  - type: web
    name: astroyorumai-api
    env: python
    plan: free    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
