# ========================================
# Render.com Deployment Configuration
# AstroYorumAI Backend Service
# ========================================

services:
  - type: web
    name: astroyorumai-backend
    env: python
    region: oregon  # Free tier available in oregon
    plan: free  # Free tier - upgrade when stable
    branch: main
    
    # Build Configuration
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt
      # Start Configuration (Free tier optimized)
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1
    
    # Environment Variables
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8080      - key: HOST
        value: 0.0.0.0
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: API_VERSION
        value: 2.1.3
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: "https://astroyorumai.com,https://www.astroyorumai.com"
      # Additional environment variables should be added through Render dashboard:
      # - DATABASE_URL (from connected PostgreSQL database)
      # - STRIPE_PUBLISHABLE_KEY
      # - STRIPE_SECRET_KEY
      # - STRIPE_WEBHOOK_SECRET
      # - OPENAI_API_KEY
      # - SENTRY_DSN
      # Health Check
    healthCheckPath: /health
    
# Note: Free tier limitations:
# - Sleeps after 15 minutes of inactivity
# - 512MB RAM limit
# - 0.1 CPU cores
# - No persistent disk storage on free tier

# Database Configuration (Free Alternative)
# Note: For free testing, use external free database services:
# 1. Supabase (2 free projects)
# 2. PlanetScale (1 free database)
# 3. Railway PostgreSQL (temporary free tier)
# 4. ElephantSQL (20MB free PostgreSQL)

# Uncomment when ready for paid database:
# databases:
#   - name: astroyorumai-postgres
#     databaseName: astroyorumai
#     user: astroyorumai_user
#     region: oregon
#     plan: starter
