services:
  - type: web
    name: astroyorumai-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn astro_api:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health
