services:
  - type: web
    name: astroyorumai-api
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 simple_api:app
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
