services:
  - type: web
    name: astroyorumai-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health
    disk:
      name: cache
      mountPath: /tmp
      sizeGB: 1