[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmd = "pip install -r requirements.txt"

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 2"
