// Mocks generated by Mockito 5.4.2 from annotations
// in astroyorumai/test/screens/birth_info_integration_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:astroyorumai/models/user_birth_info.dart' as _i5;
import 'package:astroyorumai/services/geocoding_service.dart' as _i2;
import 'package:astroyorumai/services/user_preferences_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GeocodingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeocodingService extends _i1.Mock implements _i2.GeocodingService {
  MockGeocodingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, double>?> getCoordinates(String? place) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoordinates,
          [place],
        ),
        returnValue: _i3.Future<Map<String, double>?>.value(),
      ) as _i3.Future<Map<String, double>?>);
}

/// A class which mocks [UserPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserPreferencesService extends _i1.Mock
    implements _i4.UserPreferencesService {
  MockUserPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveUserBirthInfo(_i5.UserBirthInfo? birthInfo) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserBirthInfo,
          [birthInfo],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.UserBirthInfo?> loadUserBirthInfo() => (super.noSuchMethod(
        Invocation.method(
          #loadUserBirthInfo,
          [],
        ),
        returnValue: _i3.Future<_i5.UserBirthInfo?>.value(),
      ) as _i3.Future<_i5.UserBirthInfo?>);

  @override
  _i3.Future<void> clearUserBirthInfo() => (super.noSuchMethod(
        Invocation.method(
          #clearUserBirthInfo,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
