name: Deploy to Railway Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run backend tests
      run: |
        python -m pytest backend_api_test.py -v || true
        
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        
    - name: Deploy to Railway
      run: |
        railway login --token $RAILWAY_TOKEN
        railway up --service astroyorumai-backend
        
    - name: Health Check
      run: |
        sleep 30
        curl -f https://astroyorumai-production.up.railway.app/health || exit 1
        
    - name: Test Critical Endpoints
      run: |
        python test_railway_deployment.py