name: Flutter Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
      continue-on-error: true  # Don't fail build on formatting issues
    
    - name: Analyze project source
      run: flutter analyze
      continue-on-error: true  # Log issues but don't fail
    
    - name: Run tests
      run: flutter test --exclude-tags=integration --machine > test-results.json
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Flutter Tests
        path: test-results.json
        reporter: flutter-json
